version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Build-time environment variables
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
        # Add any other build-time environment variables you need
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Runtime environment variables
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Add any other runtime environment variables your app needs
    restart: unless-stopped
    # If you need to mount volumes for data persistence
    # volumes:
    #   - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
