-- Create table for storing quiz listening data
CREATE TABLE IF NOT EXISTS quiz_listening (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT NOT NULL UNIQUE,
  responses JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index on query for faster lookups
CREATE INDEX IF NOT EXISTS idx_quiz_listening_query ON quiz_listening (query);

-- For development/migration purposes, let's allow public access
-- You can re-enable RLS after migration if needed
ALTER TABLE quiz_listening DISABLE ROW LEVEL SECURITY;

-- Create policy allowing public access for development
DROP POLICY IF EXISTS select_quiz_listening ON quiz_listening;
DROP POLICY IF EXISTS insert_quiz_listening ON quiz_listening;
DROP POLICY IF EXISTS update_quiz_listening ON quiz_listening;

CREATE POLICY select_quiz_listening 
  ON quiz_listening 
  FOR SELECT 
  USING (true);

CREATE POLICY insert_quiz_listening 
  ON quiz_listening 
  FOR INSERT 
  WITH CHECK (true);

CREATE POLICY update_quiz_listening 
  ON quiz_listening 
  FOR UPDATE 
  USING (true);
